### ISSUE TITLE
URLs

### ISSUE THREAD

**Issue by jblemee** [LateralThoughts/lt-agora#1]
Je préfère
/decisions
plutôt que : 
/decision/all

Dans les APIS :
est ce que le /v1/ est vraiment utile ?

**Comment by ogirardot** [comment]
/decisions m'en fout un peu, mais c un peu masturbatoire non :) ?
le V1 est pas forcement utile, mais ca permettra de maintenir des versions
au cas où, et ca vient à moindre coût.

2012/11/25 Jean-Baptiste Lemée notifications@github.com

**Comment by JunkieLand** [comment]
Le /decisions, c'est juste pour être plus respectueux du REST.

Le /v1/, il a pas vraiment d'intérêt vu que ce n'est pas une API ouverte.
On ne va pas casser de compatibilité avec nous même :)

Nicolas REY

Le 25 novembre 2012 11:45, Olivier Girardot notifications@github.com a
écrit :

**Comment by ogirardot** [comment]
j'accepte les pull requests, et on en discutera.
Maintenant pour répondre qd même.
techniquement pour être plus rest il faudrait alors avoir /decisions et
/decisions/1/
quant à l'api ouverte, techniquement elle va être ouverte... même si c'est
"nous" qui allons l'utiliser, ca sera pas au sein du même service forcement
(même si pour agora, je n'imagine pas encore quels services vont consommer
les APIs). après si c purement idéologique, je veux bien le renommer en
/latest lol.

**Comment by jblemee** [comment]
Bien vu l'argument "J'accepte les pull-requests" pour nous faire faire du python :P
Je crois qu'il va y avoir du débat Lundi avec Nicolas, je passerai peut être vous voir à Midi du coup ^^

**Comment by ogirardot** [comment]
c le genre de d?bat qui me saoule au point de limite changer les urls parce
que ca me saoule plus de troller que de les changer....

Le 25 novembre 2012 03:00, Jean-Baptiste Lem?e notifications@github.com a
?crit :

**Comment by hlassiege** [comment]
m'en fous je peux faire du python. En plus c'est un bon language ;)

**Comment by ogirardot** [comment]
Merci ! A part jon et un peu jb ca faisait peu de reactions positives...

**Comment by JunkieLand** [comment]
Je connais pas assez Python, et encore moins Django pour juger niveau
techno.
Mais pour l'idée je valide !

Nicolas REY

Le 25 novembre 2012 13:10, Olivier Girardot notifications@github.com a
écrit :

> Merci ! A part jon et un peu jb ca faisait peu de reactions positives...

**Comment by ogirardot** [comment]
c pas dur,
le nom de l'api est l?
https://github.com/LateralThoughts/lt-agora/blob/master/lt_agora/lt_agora/urls.py#L43

et le nom du point d'acc?s des decisions est l?
https://github.com/LateralThoughts/lt-agora/blob/master/lt_agora/lt_agora/urls.py#L36

2012/11/25 JunkieLand notifications@github.com

**Comment by jblemee** [comment]
L'inverse d'aimer étant le désintérêt, ceux qui s'intéresse au projet aiment :) Critiquer du code ou les urls n'est pas critiquer la personne, au contraire c'est signe d'intérêt pour ce que tu fais. On t'aime Olivier ;)

J'espère avoir un peu de temps la semaine prochaine avant ma mission pour rentrer un peu dans le code et faire quelques trucs. Je verrai :)

**Comment by ogirardot** [comment]
Bon donc pour conclure, les API sont restful, les urls pas forcement, mais on s'en fout c pas des APIs.
Quand à /v1/ dans l'api, normalement il n'y aura pas que le projet en interne qui utilise les APIs, donc je le garde au cas où.
Si vous voulez en discuter plus, ou en détail ouvrez moi une pull request :).
