### ISSUE TITLE
Contre proposition

### ISSUE THREAD

**Issue by jblemee** [LateralThoughts/lt-agora#16]
- Pouvoir soumettre une proposition en la liant à une proposition existante.
- Lors d'un vote -1, le site devrait proposer de créer une contre proposition (nouvelle proposition avec le champ de saisie de l'ancienne propal, prérenseigné).
- la création d'une contreproposition doit faire un apparaitre un lien vers elle dans la proposition initiale.

**Comment by ogirardot** [comment]
lol, c plus un ticket de bug, c une user story. nevermind, c'est fait, juste le point 2 n'auto-rajoute pas les données précédentes pré-renseignés.

**Comment by ogirardot** [comment]
done, déploiement ce soir, je bosse quand même...
