### ISSUE TITLE
Ce projet n'est utilisable que par des membres de LateralThoughts

### ISSUE THREAD

**Issue by mike-perdide** [LateralThoughts/lt-agora#21]
Sauf erreur de ma part, le contenu du fichier accounts/pipeline.py empêche à un utilisateur non membre de LateralThoughts de se connecter au projet tel quel :

``` python
    if not email or not email.endswith("@lateral-thoughts.com"):
        raise AuthFailed(kwargs['backend'], 'You must connect with your Lateral Thoughts account.')
```

**Comment by ogirardot** [comment]
C'est corrigé aussi, tu peux maintenant rajouté le domaine par lequel les adresses doivent être filtrés.
Le projet est conçu à la base pour google apps, avec un compte ...@lateral-thoughts.com 
si un tel domaine n'est pas accessible, il faudra étendre le projet pour rajouter une autre source d'OpenId.
Si c'est un problème pour toi, n'hésites pas à me le dire, je t'expliquerais comment faire facilement avec la lib utilisée "django-social-auth".

**Comment by mike-perdide** [comment]
Effectivement, passer par Google est un choix fait par ce projet, mais ça marche bien de mon côté, en attendant que d'autres backend d'auth soient disponibles.

Merci pour le fix.

**Comment by ogirardot** [comment]
en fait "de base" dans la lib, d'autres backend d'auth sont disponibles,
mais il faut juste les configurer
http://django-social-auth.readthedocs.org/en/latest/backends/index.html

Le 27 décembre 2012 15:01, Julien Miotte notifications@github.com a écrit
:
