### ISSUE TITLE
Image manquante lors de la première utilisation de lt-agora

### ISSUE THREAD

**Issue by mike-perdide** [LateralThoughts/lt-agora#22]
Après m'être authentifié avec mon compte Google (en ayant désactivé au préalable la restriction sur l'appartenance à LateralThoughts, voir #21), j'obtiens l'erreur suivante :

```
[Errno 2] No such file or directory: u'/root/lt-agora/lt_agora/decision_docs/DSC00072_2_1.jpg
```

```
Exception Location:     /root/.virtualenvs/agora/local/lib/python2.7/site-packages/django/core/files/storage.py in _open, line 156

In template /root/lt-agora/lt_agora/agora/templates/agora/inc_decision_detail.html, error at line 9
...
<strong>Document uploadé :</strong> <a href="{{ MEDIA_URL }}/{{ obj.document.url }}" target="_blank">{{ obj.document.name }}</a> ({{ obj.document.file.size|filesizeformat }})
...
```

**Comment by ogirardot** [comment]
c'est vrai, je vais corrigé ça. En fait la base de données de test
embarquée avec agora a été un peu poluée par moi :(
je corrige ça asap :).
Merci.

2012/12/27 Julien Miotte notifications@github.com

**Comment by ogirardot** [comment]
Corrigé. 
Maintenant la base est propre, mais ça reste une base de test, 
il faut donc configurer une source de données un peu plus "pro" pour une mise en production.
C'est configurable dans lt_agora/settings.py dans la partie DATABASES.

**Comment by mike-perdide** [comment]
Super, merci pour ta rapidité.
