### ISSUE TITLE
Configurer le projet github avec julython

### ISSUE THREAD

**Issue by ogirardot** [LateralThoughts/lt-agora#26]

**Comment by ogirardot** [comment]
done, donc ceux qui veulent peuvent commiter sur le projet et avoir des points sur le http://www.julython.org/

**Comment by hlassiege** [comment]
comprends pas, c'est quoi ?

**Comment by ogirardot** [comment]
http://www.julython.org/ c'est une initiative de la communauté python où en gros l'idée c'est de donner des points quand tu contribues sur des projets OpenSource pendant un mois donné :) 
Normalement ct en juillet mais ils font une édition en Janvier aussi cette fois ci.

J'ai configurer le projet GitHub avec les webhooks nécessaires.
Donc d'ici le premier janvier en commitant sur le projet, tu gagneras des points automatiquement. :)
