### ISSUE TITLE
Mails non reçus

### ISSUE THREAD

**Issue by jblemee** [LateralThoughts/lt-agora#9]
Je ne reçois plus les mails.

**Comment by ogirardot** [comment]
c parce que les mails sont des mails de mon serveur local, je suis en train
de parametrer la conf sur le serveur (qui ne me fournit pas de smtp)

2012/11/28 Jean-Baptiste Lem?e notifications@github.com

**Comment by ogirardot** [comment]
déploiement en cours de la dernière version.

**Comment by ogirardot** [comment]
corrigé, maintenant lt.platon.agora envoie les mails.
